#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx lint-staged || exit 1

if git diff --cached --name-only | grep -q "discogs-submitter.user.js"; then
  VERSION=$(npm version patch --no-git-tag-version | cut -c 2-)

  if [ "$(uname)" = "Darwin" ]; then
    sed -i '' "s/\(@version[[:space:]]\{1,\}\)[0-9.]*\(.*\)/\1$VERSION\2/" discogs-submitter.user.js
  else
    sed -i "s/\(@version[[:space:]]\{1,\}\)[0-9.]*\(.*\)/\1$VERSION\2/" discogs-submitter.user.js
  fi

  git add package.json package-lock.json discogs-submitter.user.js
fi
